### ISSUE TITLE
QUESTION: turn overwriting files functionality into boolean variable   

### ISSUE THREAD

**Issue by jakeschurch** [svermeulen/nvim-moonmaker#2]
pre: recently, i have started to move my nvim config over to nightly 0.5.x in order to leverage the benefits of writing my config in lua. When I heard about moonscript/moon-maker, I started to rewrite the config in moon. 

problem: by transpiling .moon files in a moon dir on the same where lua sits, e.g:

* $vim_config/
*--lua/
*--moon/

the moon files are converted into lua, and put in the lua dir. However, this rewrites any lua files in my lua dir (unexpected/unwarranted/unwanted behavior). 

---

This code seems to be the root cause: https://github.com/svermeulen/nvim-moonmaker/blob/7a6bb59286404a0ce3a69ced0e756a811bd5628b/moon/moonmaker.moon#L74-L77

I think other users besides myself will not want to use this package since overwriting files is default behavior, as well as something that is mentioned in the README/ exposed functionality to the user. 

---

Is this something that can be turned into a boolean, exposed to users to turn on and explained in the README? Is this something I can help with?

In the meantime, I am going to fork this repo and delete those lines.

Thanks~

edit: or perhaps user confirmation to clean dir/s

**Comment by svermeulen** [comment]
Yeah that's fair.  There is some risk of data loss by default right now.   I went with a user confirmation here: https://github.com/svermeulen/nvim-moonmaker/pull/3
