### ISSUE TITLE
Setting MoonMakerDeleteOrphanedLuaFiles in Lua does not suppress message

### ISSUE THREAD

**Issue by alecStewart1** [svermeulen/nvim-moonmaker#6]
I have the following setup in with packer.

```
use {                                       
    'svermeulen/nvim-moonmaker',          
    setup: () ->                                          
        g.MoonMakerDeleteOrphandLuaFiles = 1
}                                           
```

And `setup` allegedly runs _before_ the package is loaded. So one would think the popup message would go away by setting `MoonMakerDeleteOrphanedLuaFiles`, but it doesn't seem to.

**Comment by svermeulen** [comment]
You're right, that flag was not working as described.  This should be fixed now.  Also - you'll need to rename `MoonMakerDeleteOrphandLuaFiles ` to `MoonMakerDeleteOrphanedLuaFiles` in your script there
